version: '3'
services:
  container:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"  # 服务端口
    environment:
      - VITE_APP_API_BASE_URL=${VITE_APP_API_BASE_URL}
      - VITE_APP_DEFAULT_USERNAME=${VITE_APP_DEFAULT_USERNAME}
    restart: unless-stopped
    networks:
      - amadeus-network
    volumes:
      - ./logs:/app/service/logs  # 如果需要持久化日志
networks:
  amadeus-network:
    driver: bridge